### ISSUE TITLE
existing account not found

### ISSUE THREAD

**Issue by convolvatron** [moonlightwork/bug-tracker#1]
I received a mail at yuri@tenuki.org about a Project Match. so, I attempted
to sign in at moonlightwork. however, the email/password combination was
not accepted, and attempts to use the email to reset my password failed.

i assume I still have some account information active (in order to be matched), but
I can't log in to responsd

**Comment by philipithomas** [comment]
Hey @convolvatron  - we are still in limited availability with the application. So, most contractor accounts haven't been imported yet. You should receive an invitation to setup an account in the next two weeks. 

In the mean time, if you need to make any changes, or if you have any questions - please email us at team@moonlightwork.com
