### ISSUE TITLE
Can't set up Stripe from my country

### ISSUE THREAD

**Issue by adam-arold** [moonlightwork/bug-tracker#10]
I tried to register to the site but there are no payment options besides Stripe and it is not supported in my country (Hungary). How can I register?

**Comment by philipithomas** [comment]
Hi Adam,

To register, you need a Stripe account. So, if you are not in one of Stripe's [supported countries](https://stripe.com/global), then you could set up a company in one of the supported countries to create an account (e.g. Stripe Atlas or an Estonian E-Corp). 

This is a known issue and we hope to expand payment options at some point. We track signups by country and will let you know when we add support for Hungary.
