### ISSUE TITLE
Message window

### ISSUE THREAD

**Issue by JJThaeler** [moonlightwork/bug-tracker#11]
If you use moonlightwork.com, you can use this repo to report and track bugs in the application, or to browse known issues. If the bug is security-related, please send a private report to team@moonlightwork.com.

### Which browser are you using? Chrome Version 70.0.3538.102 whatsmybrowser.org/b/6C53BB3

If applicable - please share a link from http://www.whatsmybrowser.org

### What are the steps to reproduce the issue?
Clicking on message candidate after a decline. Message box throws error 13 initially but can be reloaded, only there's no text input available in the chat

**Comment by philipithomas** [comment]
Thanks @JJThaeler! I'll take a look at this.

**Comment by philipithomas** [comment]
Hey @JJThaeler - thank for this report. We have decided to spend this week starting to rewrite how jobs and interviews work in the app. So, we are actually going to be ripping out this interface and replacing it with something new. So, I'll make sure the next version does not have this bug. But, for now, I'm not going to fix this. 

If you ever want to message a user - you can go to their profile and click "Message"!
