### ISSUE TITLE
Stripe<>Firefox Onboarding Issues: Stripe signup step of enrollment process fails with "Expired Link" error

### ISSUE THREAD

**Issue by dougwebb** [moonlightwork/bug-tracker#2]
I'm trying to get through the initial contractor enrollment process. I'm using the latest Firefox on Win10.

When the enrollment hands off to Stripe, the first page requests Mobile # and email address. When submitting that page, the response is an error page that says "the link is expired".  There are no links to go back, or to try again, and the link for reporting a problem just goes to Stripe's FAQ.

I thought the problem might be because I was sent to Stripe before I got the confirmation email from Moonlight and I confirmed my account, but after confirming my account I was handed off to Stripe again, filled out the same form, and got the same error.

Maybe a dev key was deployed for the handoff to Stripe instead of a production key? I haven't used this part of their API, but I could see a mistake like that causing the error I'm seeing. The email asking me to signup for Moonlight is only three days old, so I don't think I've passed a time limit for signing up.

**Comment by philipithomas** [comment]
@dougwebb Can you email us directly (team@moonlightwork.com) the actual link that you are being directed to? We can see if it's malformed.

Many people have setup this integration, so it's not 100% broken. However, we have seen some issues - and it's not clear whether it's on our end or Stripe's. 

Similar users have succeded in this step using Chrome - can you try that?

**Comment by dougwebb** [comment]
Emailed some details. Yes, Chrome did get me through the process with fewer issues.

**Comment by philipithomas** [comment]
We have more reports of firefox issues:

```
I tried going through the enrollment using Chrome, which sort-of worked.

...

The Stripe pages seemed to work ok; I filled out the info and was redirected to https://www.moonlightwork.com/onboarding/connect-stripe. But this seems to have left me back where I started, asking me to sign up in Stripe. Clicking the button on that page takes me back to the first Stripe form.

I went back to Firefox, logged out of Moonlight, and logged back in. I'm past the enrollment process now, and got to my profile page. So, I seem to have managed to enroll fully, but it wasn't exactly a smooth process.
```
([internal tracking link](https://app.intercom.io/a/apps/o8eup5pb/respond/inbox/all/conversations/12825450555). )

We'll spend some time testing on Firefox and trying to understand this issue. I bet it's a bug that Chrome silently handles, but Firefox does not.

**Comment by philipithomas** [comment]
I think that this issue has been resolved - please reopen if you still encounter it.
