### ISSUE TITLE
Cannot update profile photo on contractor profile

### ISSUE THREAD

**Issue by apaatsio** [moonlightwork/bug-tracker#4]
### Which browser are you using?

I tried two browsers and the problem arises on both.

Chrome 66.0.3355.0 (Linux)
Firefox 58.0.2 (Linux)

### What are the steps to reproduce the issue?

1. Login as contractor
2. Open your profile
3. Click 'edit profile'
4. Click 'change photo'
5. File selection dialog appears. Select jpg image and click Open.
6. Click Save

Actual outcome: Profile photo does not change.
Expected outcome: Profile photo changes to the photo selected in step 5.

**Comment by philipithomas** [comment]
Thanks for the clear reproduction steps. This is definitely broken. Will post an update when it has been fixed.

**Comment by philipithomas** [comment]
this seems to be related to this bug in the Buefy library:

https://github.com/buefy/buefy/issues/575

They haven't cut a new release with the fix yet, so we will patch it until it's fixed.

**Comment by philipithomas** [comment]
Deploy on its way out with a fix - thanks for the bug report @apaatsio !
