### ISSUE TITLE
Deal breaker - Sign up requires account on Stripe which does not support all countries!

### ISSUE THREAD

**Issue by arpitux** [moonlightwork/bug-tracker#5]
I am based out in India where largest population of freelancers live. Unfortunately signing up on 
Moonlightwork requires to have an account on Stripe and it does not serve India.

**Comment by philipithomas** [comment]
This isn't something broken, it's just a trade-off in the payment systems we use. We are aware and will be adding additional payout methods in the future. 

We do have support for India - you just have to join their beta: https://stripe.com/blog/india-private-beta

**Comment by arpitux** [comment]
Stripe's beta is on invites only. Well I have received invitation to join Moonlightwork before Stripe's invite.. :)
