### ISSUE TITLE
Field validation crashes the profile editing page

### ISSUE THREAD

**Issue by dsmaher** [moonlightwork/bug-tracker#8]
Field validation shows an error at the top of the page, but clears the page of all profile fields.  Clearing the error does not restore the fields.

### Which browser are you using?
Chrome 65 on Windows

### What are the steps to reproduce the issue?
Update profile and set an invalid year... Like 205 or anything prior to 1991.

**Comment by philipithomas** [comment]
Thanks - the 1990 lower limit on experience years is a silly mistake. I'm pushing a fix that drops it to 1900, and I'll work on better validation on the front-end.

**Comment by philipithomas** [comment]
We have a change going live right now that fixes this bug. Thanks for the report!
